[package]
name = "p2p-handshake-123"
version = "1.0.0"
authors = ["ghz"]
edition = "2018"

[dependencies]
bitcoin_hashes = "0.11.0"
chrono = { version = "0.4.19", features = ["serde"] }
tokio = { version = "1.14", features = ["full"] }
